[package]
name = "probranchinator"
description = "A tool to help you analyse conflicts in git branches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = { version = "0.16.1", features = ["ssh"] }
tui = "0.19"
crossterm = "0.25"
tempfile = "3.5.0"
anyhow = "1.0.70"
clap = { version = "4.2.0", features = ["derive"] }
ssh2 = "0.9.3"
