on:
  push:
  # release:
  #   types: [created]

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache
        uses: actions/cache@v3
        with:
          key: all-caches
          path: |
            ./target
            ~/.cargo
            ./cross
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - run: cargo install cargo-make
      - run: cargo make install-cross
      - run: cargo make build-linux_x86_64
      - run: cargo make build-windows_x86_64
      - run: cargo make build-mac_x86_64
        env:
          CACHE_TO: type=gha,mode=max,scope=mac_x86_64
          CACHE_FROM: type=gha,scope=mac_x86_64
      - run: cargo make build-mac_arm
        env:
          CACHE_TO: type=gha,mode=max,scope=mac_arm
          CACHE_FROM: type=gha,scope=mac_arm
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target/**/release/probranchinator
      - name: Read changelog
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ (github.ref_type == 'tag' && !contains(github.ref_name, '-') && github.ref_name) || 'Unreleased' }}
          path: ./CHANGELOG.md
      - run: gh release delete --yes Unreleased || exit 0
        if: >
          github.event_name == 'push' &&
            github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
      - name: Create GitHub release
        if: >
          github.event_name == 'push' && (
            github.ref == format('refs/heads/{0}', github.event.repository.default_branch) ||
            startsWith(github.ref, 'refs/tags/v')
          )
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ (github.ref_type == 'tag' && github.ref_name) || 'Unreleased' }}
          body: ${{ steps.changelog-reader.outputs.changes }}
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref_name, '-') }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/v') && steps.changelog-reader.outputs.status == 'unreleased' }}
          files: |
            target/**/release/probranchinator
      
