on:
  push:
  # release:
  #   types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cargo install --force cargo-make
      - run: cargo make install-cross
      - run: cargo make build-all
