on:
  push:
  # release:
  #   types: [created]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache
        uses: actions/cache@v3
        with:
          key: all-caches
          path: |
            ./target
            ~/.cargo
            ./cross
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - run: cargo install cargo-make
      - run: cargo make install-cross
      - run: cargo make build-linux_x86_64
      - run: cargo make build-windows_x86_64
      - run: cargo make build-mac_x86_64
        env:
          CACHE_TO: type=gha,mode=max,scope=mac_x86_64
          CACHE_FROM: type=gha,scope=mac_x86_64
      - run: cargo make build-mac_arm
        env:
          CACHE_TO: type=gha,mode=max,scope=mac_arm
          CACHE_FROM: type=gha,scope=mac_arm
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target/**/release/probranchinator
      
