on:
  push:
  # release:
  #   types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cargo install --force cargo-make
      - run: cargo make install-cross
      - run: cargo make build-all
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            **/target
            ~/.cargo
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target/**/release/probranchinator
      
