on:
  push:
  # release:
  #   types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache
        uses: actions/cache@v3
        with:
          key: all-caches
          path: |
            ./target
            ~/.cargo
            ./cross
            ./docker-cache
      - run: cargo install cargo-make
      - run: cargo make install-cross
      - run: cargo make build-all
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target/**/release/probranchinator
      
